feat(Validium): Adding CI jobs for running integration tests in Validium mode
matter-labs/zksync-era pull request #1312
Opened 2024-03-01 11:51 UTC by jordibonet-lambdaclass

## What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.
- [ ] Spellcheck has been run via `zk spellcheck`.
- [ ] Linkcheck has been run via `zk linkcheck`.

2024-03-01 21:47 UTC, ilitteri requested changes
`ci-integration-tests-validium.yml` looks fine, but it is not enough for the CI to run it. We still need to modify `ci.yml`. Take a look at this to use as reference https://github.com/lambdaclass/zksync-era/pull/159/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR88

2024-03-05 18:49 UTC, jordibonet-lambdaclass commented
While adapting the CI for Validium of the integration tests and the external node, we found a problem with the connection string for the databases: in Rollup it was `postgres://postgres@postgres/prover_local` and in Validium `postgres://postgres@localhost/prover_local`.
We fixed it with the configuration file `dev_validium_docker.toml`, adding the same configuration as `docker.toml`.

Currently we have two doubts:
- We can't find where the connection string for databases has been configured to be `postgres://postgres@localhost/prover_local`.
- The contracts submodule seems not to be pointing to the right commit despite it is correctly set in `.gitmodules`, which causes the `Verifier` deployment to fail, because we need the deployment to take a parameter that has been added now, which is `--validium-mode`. You can check it in the [last CI run](https://github.com/matter-labs/zksync-era/actions/runs/8160772169/job/22308165141?pr=1312). Is the submodule commit being updated somewhere else than in the _Checkout system-contracts submodule step_?

2024-03-05 19:36 UTC, ilitteri commented
>     * The contracts submodule seems not to be pointing to the right commit despite it is correctly set in `.gitmodules`, which causes the `Verifier` deployment to fail, because we need the deployment to take a parameter that has been added now, which is `--validium-mode`. You can check it in the [last CI run](https://github.com/matter-labs/zksync-era/actions/runs/8160772169/job/22308165141?pr=1312). Is the submodule commit being updated somewhere else than in the _Checkout system-contracts submodule step_?

Probably there's something wrong with the commit that is pushed, I'll double check this

2024-03-06 06:08 UTC, popzxc commented
@jordibonet-lambdaclass I think that by default the prover database URL is taken from `etc/env/private.toml` 

![image](https://github.com/matter-labs/zksync-era/assets/12111581/b017fcc0-ab45-4786-ae2d-b98f238bec11)

2024-03-06 14:22 UTC, jordibonet-lambdaclass commented
Thank you @popzxc. 
Apologies, I made a mistake, we were actually referring to the other one (`postgres://postgres@postgres/prover_local`). 
We can't find in which part of the CI it is assigned that one and not the default one in `private.toml`.

2024-03-07 06:11 UTC, popzxc commented
@jordibonet-lambdaclass I'm not sure if I fully understand the issue, but as a rough hypothesis: recently we've changed the approach to the databases, instead of using "trust" auth method everywhere, we introduced a hardcoded password ("no secure password"). The connection string you mentioned has no password in it, so maybe you're trying to use an old connection string somewhere. If you're interested to see where the Postgres in configured in general, then it's [this docker-compose file](https://github.com/matter-labs/zksync-era/blob/main/docker-compose.yml).

If that doesn't help, please elaborate what you're trying to do, what goes wrong, and what would you expect to work.

2024-03-13 21:55 UTC, ilitteri commented
The integration tests that are failing are fixed in https://github.com/matter-labs/zksync-era/pull/1270 and https://github.com/matter-labs/zksync-era/pull/1296. We can wait for #1270 to be merged to pull from the base branch, but this PR can be reviewed in the mean time

2024-03-14 07:23 UTC, popzxc reviewed
Generally looks good, let's wait for all the prerequisites to be merged.

2024-03-14 07:23 UTC, popzxc commented on core/tests/ts-integration/tests/api/web3.test.ts
> +    // test('Should check transactions from API / Legacy tx', async () => {
Don't forget to uncomment later.

2024-03-14 12:48 UTC, popzxc approved these changes
I'll approve this PR tentatively to not block you -- feel free to merge as soon as you feel it's ready.
If there will be any issue with it post factum, we'll catch them during the review of the main PR.

2024-03-22 20:35 UTC, merged