feat(ci): Deprecate zk
matter-labs/zksync-era pull request #2860
Opened 2024-09-12 12:56 UTC by Deniallugo

## What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.

2024-09-16 11:40 UTC, perekopskiy requested changes

2024-09-16 11:40 UTC, perekopskiy commented on .github/workflows/ci-core-reusable.yml
> -          echo RUN_CONTRACT_VERIFICATION_TEST=true >> .env
it seems contract verification tests are not run at all with your changes

2024-09-16 11:56 UTC, artmakh submitted a review, later dismissed

2024-09-16 12:34 UTC, Deniallugo commented on docs/guides/external-node/building-from-scratch/Dockerfile
> +RUN zk_supervisor contracts|| true
hm, seems it's not needed you are right

2024-09-17 08:25 UTC, perekopskiy approved these changes

2024-09-17 09:11 UTC, artmakh approved these changes

2024-09-17 09:38 UTC, merged