feat(tee): add support for recoverable signatures
matter-labs/zksync-era pull request #3414
Opened 2024-12-30 14:28 UTC by pbeza

## What ❔

Signatures produced by the TEE Prover are now compatible with on-chain ecrecover.

## Why ❔

Until now, we’ve been using non-recoverable signatures in the TEE prover with a compressed (ECDSA) public key in each attestation – it was compressed because there are only 64 bytes available in the report attestation quote. That worked fine for off-chain proof verification, but for on-chain verification, it’s better to use the Ethereum address derived from the public key so we can call `ecrecover` in Solidity to verify the signature.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] Code has been formatted via `zkstack dev fmt` and `zkstack dev lint`.

2025-01-07 12:53 UTC, haraldh requested changes

2025-01-07 12:53 UTC, haraldh commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +                let signature = TeeProver::sign_message(&self.config.signing_key, msg_to_sign)?;
How about `self.sign_message()` which then has access to `self.config.signing_key`??

2025-01-10 14:27 UTC, slowli commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +        let s = SECP256K1.sign_ecdsa_recoverable(&message, sec);
You can use [the `zksync_crypto_primitives` library](https://github.com/matter-labs/zksync-era/blob/main/core/lib/crypto_primitives/src/ecdsa_signature.rs); it has this functionality (and one used in the unit tests below) implemented.

2025-01-10 14:27 UTC, slowli commented on core/bin/zksync_tee_prover/Cargo.toml
>  zksync_types.workspace = true
Slightly off-topic: You can remove this dependency and instead rely on `zksync_basic_types` to speed up compilation somewhat.

2025-01-14 15:38 UTC, pbeza commented on core/bin/zksync_tee_prover/Cargo.toml
>  zksync_types.workspace = true
[Removed](https://github.com/matter-labs/zksync-era/pull/3414/commits/27ad86ec8d7aefc1c8bcf5e971670209681c92ad#diff-5948891da9d6c6726f73866f6f4854fd3a059756442499105403090d41e221dd). ✅

2025-01-17 14:33 UTC, pbeza commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +        let s = SECP256K1.sign_ecdsa_recoverable(&message, sec);
@slowli, kindly `ping`.

2025-01-20 09:24 UTC, slowli commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +        let s = SECP256K1.sign_ecdsa_recoverable(&message, sec);
The existing primitives are private because so far, there was no use case to make them public, and keeping stuff private by default is a good practice. Now that such a use case has appeared, I'd suggest to make the necessary primitives public and export them from `crypto_primitives`.

2025-01-31 12:53 UTC, slowli reviewed
Other than what looks like an overly complex construction of a secret key, looks good 👍

2025-02-05 22:53 UTC, pbeza commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +            .map_err(|e| TeeProverError::Verification(e.into()))?;
[Fixed](https://github.com/matter-labs/zksync-era/pull/3414/commits/b4fcf43cac49b29ad172585f0b74edb3011dbf75). ✅ Please re-review.

2025-02-06 11:47 UTC, slowli submitted a review, later dismissed

2025-02-06 18:00 UTC, pbeza commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +            .map_err(|e| TeeProverError::Verification(e.into()))?;
[Fixed](https://github.com/matter-labs/zksync-era/pull/3414/commits/1f00597738bc2574e0a6044c0ad0c5aac310344d). ✅

2025-02-06 18:01 UTC, pbeza commented on core/bin/zksync_tee_prover/src/tee_prover.rs
> +        assert!(private_key.address() == expected_address);
[Fixed](https://github.com/matter-labs/zksync-era/pull/3414/commits/1f00597738bc2574e0a6044c0ad0c5aac310344d). ✅

2025-02-06 18:37 UTC, slowli approved these changes

2025-02-07 12:06 UTC, pbeza commented
JFYI, @haraldh, it's ready to merge. ✅🫡

2025-02-17 14:48 UTC, haraldh approved these changes

2025-02-17 15:30 UTC, merged