WIP: separate DAL for Prover and Main server
matter-labs/zksync-era pull request #369
Opened 2023-11-01 10:46 UTC by AnastasiiaVashchuk

2023-11-09 16:18 UTC, AnastasiiaVashchuk commented on core/lib/db_utils/src/instrument.rs
> -            .unwrap();
these tests are moved to tests in `server_dal` crate

2023-11-09 16:25 UTC, AnastasiiaVashchuk commented on core/lib/server_dal/src/blocks_dal.rs
> -
https://github.com/matter-labs/zksync-era/pull/369/files#r1388250810

2023-11-30 14:39 UTC, Deniallugo requested changes
It's Titanic job! Well done!
Please review it by yourself one more time a bit more careful.

2023-11-30 14:39 UTC, Deniallugo commented on core/lib/zksync_core/src/proof_data_handler/mod.rs
> +    pool: ServerConnectionPool,
proof data handler with server?

2023-11-30 14:39 UTC, Deniallugo commented on core/lib/zksync_core/src/witness_generator/basic_circuits.rs
> +    let witness_gen_input = build_basic_circuits_witness_generator_input(
@EmilLuta could you double that it's the correct pool

2023-11-30 14:39 UTC, Deniallugo commented on docs/architecture.md
> +    - `/server_dal`: Data availability layer
we have to include prover dal somewhere as well

2023-11-30 14:39 UTC, Deniallugo commented on etc/env/base/rust.toml
> +zksync_server_dal=info,\
add prover_dal as well

2023-11-30 14:39 UTC, Deniallugo commented on etc/system-contracts
please don't change it

2023-11-30 14:39 UTC, Deniallugo commented on prover/witness_generator/src/main.rs
> +                server_connection_pool,
prover?

2023-11-30 14:39 UTC, Deniallugo commented on prover/witness_generator/src/basic_circuits.rs
> +        connection_pool: ProverConnectionPool,
Server?

2023-12-04 15:23 UTC, AnastasiiaVashchuk commented on core/lib/db_connection/src/lib.rs
> -}
moved here - https://github.com/matter-labs/zksync-era/blob/5ab5c9a64eb5212204116ddc87aa132c0b1d7ae4/core/lib/server_dal/src/tests/mod.rs#L307

2023-12-04 15:49 UTC, AnastasiiaVashchuk commented on core/lib/server_dal/src/protocol_versions_dal.rs
> -    }
moved to `prover_dal`

2023-12-04 15:49 UTC, AnastasiiaVashchuk commented on core/lib/server_dal/src/protocol_versions_dal.rs
> -    }
moved to `prover_dal`

2023-12-04 17:01 UTC, AnastasiiaVashchuk commented on core/lib/zksync_core/src/metadata_calculator/mod.rs
> +        // short-term change for the prover pool
https://linear.app/matterlabs/issue/PLA-677/come-up-with-a-proper-solution-for-running-tree-with-a-prover-pool-in

2023-12-05 13:02 UTC, AnastasiiaVashchuk commented on core/lib/server_dal/src/healthcheck.rs
> +use serde::Serialize;
i thought about it, but not sure how to implement it

2024-02-07 12:53 UTC, popzxc commented
Will be tackled as a sequence of smaller PRs

2024-02-07 12:53 UTC, closed without merging